### ISSUE TITLE
 Contact Control Panel Logged out error in IFrame

### ISSUE THREAD

**Issue by sid95ok** [amazon-connect/amazon-connect-streams#130]
We are using Amazon Connect Streams API (Streams) and have embedded the Contact Control Panel (CCP) UI components into the application. Although it was working fine till we noticed that when the agent is not logged in or goes offline and comes again on the page since the session is logged out, the page shows an error in connecting with the instance.

We also have whitelisted our domain in amazon connect application integration 

![Screenshot from 2019-08-02 12-50-25](https://user-images.githubusercontent.com/35728090/62359628-d3ed9380-b534-11e9-9dcf-bb982f646a8b.png)

**Comment by sid95ok** [comment]
We want to have login either inside the IFrame or we want some control over this authentication event so that we can handle this error gracefully

**Comment by siddiq-syed** [comment]
what is the process you following for the logout ? 

I am getting the same error when I call logout manually. There should be some clean way to logout and login back again.

https://<>.awsapps.com/connect/logout

**Comment by sid95ok** [comment]
I am logging out through CCP window and also when I am not logged in at that time also integrated IFrame shows error and that is not a good user experience.

**Comment by siddiq-syed** [comment]
yeah I have the same issue... the loginPopup doesn't work either.

I get
 Refused to display 'https://<>.awsapps.com/connect/login?landat=%2Fconnect%2Fccp#/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

I create and delete the agent everytime they want login and logout.

**Comment by jagadeeshaby** [comment]
Agreed this is a valid Concern for SAML auth and this needs to solved from the library. 

Here is the code which Causes this issue for SAML login - https://github.com/aws/amazon-connect-streams/blob/master/src/core.js#L302

this needs to take care of whether to reload the page or open a login popup to re-authenticate the user. (and Provide a dedicated event for the same) -  Currently it just reloads and hence CCP does not know how to authenticate the SAML user and redirects to a access denied page which is not enabled for XFraming.(other directory logins works because we have a dedicated login page for the same)   

Interim you can use below event to determine the ACK timeout use case. 
 
connect.core.getEventBus().subscribe(connect.EventType.ACK_TIMEOUT, function() {
  // Triggered when ACK fails (needs re-login)
  // Use this to handler hide the CCP or show some custom message or popup the login window to re login 
})

**Comment by imankurpatel000** [comment]
@jagadeeshaby 
I am not using SAML but still, when a user logs out from the CCP, there doesn't seem for my app to know that the user has logged out. The ACK_TIMEOUT is also not occurring. Here is a screen shot of the same.
![image](https://user-images.githubusercontent.com/37868387/71436638-565d3680-2714-11ea-8965-a66ecd21ebcc.png)

The First ACK_TIMEOUT that you see is when I first loaded the page, it opened a second tab for the user to login but user accidently closed the login page, now there is no way for me to know the login has not happened. The same issue happens if I logout from the CCP. It just keeps trying to load the login page inside the IFrame but doesn't give any event from which I can detect if the user is logged in or not.
