### ISSUE TITLE
Check authentication failed while using SAML Authentication.

### ISSUE THREAD

**Issue by shreyasbhatia09** [amazon-connect/amazon-connect-streams#144]
Is there a way to programmatically check whether there was an error while logging in using SAML authentication? I tried to subscribe through the event bus to AUTH_FAIL but did not receive any events when the SAML authentication failed.

**Comment by camstuart** [comment]
Not that I have encountered, the best I can do is examine: 

`connect.agent.initialized` 

it's no guarantee that there wasn't some other init problem, but if that is `false` then you know something is up

**Comment by jagadeeshaby** [comment]
You could try the following 

```
 connect.core.getEventBus().subscribe(connect.EventType.ACK_TIMEOUT, function() {
   // Triggered when ACK fails (needs re-login)
   // Use this to handler hide the CCP or show some custom message or popup the login window to 
   // re login 
 });

```

Connect team is  also working on the solution to have a more intuitive/dedicated login failure handler like below

```
 connect.core.onAuthFail(() =>{
   // requires login
 })
```

**Comment by marcogrcr** [comment]
It seems that 7f104fc added [two handlers](https://github.com/marcogrcr/amazon-connect-streams/commit/7f104fc04a85ae838fb1e37a6a7d36b279aae4fe#diff-7eb52b366866677666470e019283c8eaR699-R712):

- `connect.core.onAuthFail`
- `connect.core.onAccessDenied`

They seem to be hooked up on [worker.js](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/worker.js).

Are these methods supported?

**Comment by marcogrcr** [comment]
#243 officially documented the handlers, so this can be closed.

**Comment by Christian-Sesta** [comment]
It is great that we now have these handlers been wanting for a while.

Since this ticket is similar to an issue I was just about to raise I thought it should go here as it directly refers to those two handlers. It seems that neither of these two handlers cater for the first issue in this error [Error Message: Access Denied. Your account has been authenticated, but has not been onboarded to this application.](https://docs.aws.amazon.com/connect/latest/adminguide/troubleshoot-saml.html) specifically around the point `the user not existing in amazon connect.`.

Currently in my system if a user is successfully authenticated but does not exist in the system neither of the two handlers fire at all.

**Comment by bbolek** [comment]
Hey its been more than a year,
Is there any ETA for this issue?

Thanks
