### ISSUE TITLE
Integration with app in electronjs

### ISSUE THREAD

**Issue by armcv** [amazon-connect/amazon-connect-streams#166]
I need to know if it is possible to use this app to create an agent as an application in electronjs. In the tests I have done this error appears: X-Frame-Options: “SAMEORIGIN”.

**Comment by hfahlbusch** [comment]
Have you read the Getting Started Guide on this page? 
And added your domain to the whitelist?

[https://github.com/aws/amazon-connect-streams#getting-started](https://github.com/aws/amazon-connect-streams#getting-started)

**Comment by ctwomblyamzn** [comment]
Thank you for the helpful answer, @hfahlbusch. We agree that the issue is likely that you have not whitelisted your outer domain. Please let us know if it persists once you have tried following the steps outlined in [the getting started guide](https://github.com/aws/amazon-connect-streams#getting-started).

**Comment by jolim24601** [comment]
It looks like two possible options right now are to wait for login/logout functionality to be released so you don't have to embed CCP in an iframe anymore (#13) or to allow `*` as an origin though this would introduce an additional risk to your instance. I will follow up with the team that controls the second option and post an update here since currently that is not allowed.

**Comment by jolim24601** [comment]
We do not currently have plans to support wildcards so the most likely scenario is a release of native CCP in the future or a release of Streams that removes the iframe behavior.
