### ISSUE TITLE
How can I access the data of other connected agents?

### ISSUE THREAD

**Issue by clegeard** [amazon-connect/amazon-connect-streams#18]
Hi,

How can I get the data of other agents connected to the CCP?
I would like to transfer call between agents, but I can't find how to see if there are other agents connected or not. 
I tried to use agent.getContacts(), but it returns an empty array.
Thanks

**Comment by sromocki** [comment]
I second this question.  I can transfer the call to another agent if I have their desk phone number by creating an endpoint and using the agent.connect API.  However, if I want to transfer the call to an agent using only the softphone, I don't see a way to do this.

**Comment by naresh-talluri** [comment]
@clegeard agent.getContacts() gets you all inbound/outbound calls you made on the recent conversation, i don't think amazon connect having a way to find the available status of other agent.

**Comment by ninjamike54** [comment]
There isn't currently a way to query for agents beyond the authenticated agent as it exists today. Transferring to agents is currently available only as a pre-configured Quick connect option (when you create a Quick connect you can make it an "agent" type and specify to which agent you want the transfer to go), but beyond that we have no dynamic hooks built into the streams API. 

I'll make sure to track this as a feature request, and update this when we know more.

**Comment by mschersten** [comment]
As a possible workaround, you could theoretically build your own API to at least present agent availability data to other agents.  The agent event kinesis stream would work, but best case scenario is that data might be up to a minute old.  If everyone is using a custom panel, you could have those write the agent status, maybe onRefresh(), to an external database, and present that to the agents through the custom panel.

From there, maybe the agent would just find another available agent and transfer to them as a quick-connect.  Streams offers Endpoint.byPhoneNumber(), but we would want something like Endpoint.byAgentLogin() so that we could use that in contact.AddConnection().

**Comment by camstuart** [comment]
+1 I'm looking for a way to create an endpoint of type agent as well

**Comment by hngan** [comment]
it’s been a while andwe are closing this for now. Please reopen if it’s still an issue
