### ISSUE TITLE
How do I get the contact id of a contact created by agent.connect()?

### ISSUE THREAD

**Issue by gituser5513** [amazon-connect/amazon-connect-streams#216]
When I call:
```
agent.connect(endpoint, {
   queueARN: QUEUE_ARN,
   success: function() { ... },
   failure: function() { ... }
});
```
How do I get the contact id of the dialed contact? The `success` callback doesn't seem to include it.

**Comment by faizaanshah** [comment]
I dont think your question is clear, but getContactId() is available in both contact as well as connection..

**Comment by gituser5513** [comment]
Is it safe to assume that when I call
```
agent.connect(endpoint, {
   queueARN: QUEUE_ARN,
   success: function() { ... },
   failure: function() { ... }
});
````
The next contact received by this method will be the one that was dialed?
```
connect.contact(function(contact) { ... });
```
Is there any chance of a race condition where the agent receives an inbound milliseconds after they call `agent.connect()` and thus the `connect.contact()` call returns the wrong contact?

**Comment by andersonjohnf** [comment]
I am running into this same issue. I do not understand why the success handler for agent.connect does not pass the contact object.  That would definitely be the optimal design, rather than a success handler with zero arguments and hoping for no race condition in the event handlers.

**Comment by 0-g-r-e-g-0** [comment]
I have never had any issue with using agent.connect() to start a call, and waiting for the contact notification through my registration via connect.contact(). No race conditions. You either get a failure callback, or a new contact notification some small amount of time later.

**Comment by andersonjohnf** [comment]
Just because there hasn't been an issue yet doesn't mean there won't be, or that the design is optimal. I can't think of a good reason not to pass the contact object to the success handler.  Can you?

**Comment by 0-g-r-e-g-0** [comment]
I do things a bit differently to you: I only call connect.contact() in my connect.agent() handler - not per call.
So far I have no reports of failures to make calls from production agents.
I have always assumed that we don't get the contact in the success handler because it doesn't exist yet. I only use the success handler to generate a log message.
My guess is that the connect call only kicks off the process of setting up a new connection/contact after doing some basic checks.  I never worried about it because it is a common model for CTI solutions: you instruct it to make a call, and a bit later you get one or more events that tell you that a call is in progress. I've seen this model used by 3 other CTI providers.
