### ISSUE TITLE
Initialize CCP using a token, skip login?

### ISSUE THREAD

**Issue by crrice** [amazon-connect/amazon-connect-streams#239]
Is there a way to log users into the CCP using a token (or other info) directly?

The problem is that our webapp needs to include the CCP but also needs to access other AWS APIs for which separate authentication is required. We have SAML SSO set up to authenticate users with AWS generally (via Cognito) which grants access those APIs.

Our backend is capable of calling `getFederationToken` on the user's behalf, but there is no way to use that to initialize the CCP. Asking the user to login to the app and ccp separately is (being a master of understatement) less than ideal. I'm looking for a way to use a token to start the CCP without requiring a second, separate login flow.

[This comment on another issue](https://github.com/amazon-connect/amazon-connect-streams/issues/13#issuecomment-385511106) makes it sound like might this is possible.

> It's possible to programmatically sign in and initialize the Streams library with that authentication context (via SAML / SSO which I linked above and has fully launched at this point)...

But it doesn't go into detail. Can someone elaborate on how it would be accomplished, or if it's even possible at all?

----

[Related Github Issue](https://github.com/amazon-connect/amazon-connect-streams/issues/116), but the `loginUrl` parameter does not address this problem.

**Comment by blee-amzn** [comment]
Hi crrice,

You cannot use that token (or aws credentials) to authenticate with Amazon Connect. Amazon Connect [does support SAML/SSO authentication](https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html), so if you can find a way set this up in your instance as described in the doc you should be able to avoid that second login screen.

Please let me know if this helps!

**Comment by blee-amzn** [comment]
Closing this issue, please let me know if you have any additional questions.

**Comment by faizaanshah** [comment]
Hey @blee-amzn  since you mentioned by using [SSO](https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html) we can avoid login page. We have been doing same. By using third party saml provider we had been able to authenticate our user which solves the problem of amazon connect default login page.

After authenticating from the SAML provider, we get an authentication token plus a sign in link, when we click on that link we are redirected to connect-ccp which opens for some time untill we close it down via some javascript code.

Now we dont want to use that sign in link provided by the SAML provider but we want to use the token provided to authenticate from the streams library without opening CCP.

Is there possible undocumented way by twitching code a little? We couldn't find a way out yet.

Thanks.

**Comment by blee-amzn** [comment]
Hey @faizaanshah, please see [this issue](https://github.com/amazon-connect/amazon-connect-streams/issues/267) for discussion on this topic. In short, it may be possible by embedding the SAML login url but there are also security risks associated with doing so.
