### ISSUE TITLE
Upgrading Streams API - Unable to Connect to Customer

### ISSUE THREAD

**Issue by amicming** [amazon-connect/amazon-connect-streams#266]
Hello,

We are currently in the process of upgrading the connect-streams API in our custom CCP (Angular app). The previous version was pulled from the connect repo in August 2019. After pushing the latest version of the API into our application we initially saw a few type definition compile errors. This was expected and now is resolved. Also, after the change we aren't seeing any issues with initializing the CCP from what we can tell.

Currently, our development is blocked since we can't establish connection between customer and agent.  On incoming calls the UI recognizes the state change from 'Ready' to 'PendingBusy' but then immediately after the whole app freezes with no Error messages. 

Any idea? Suggestion?

**Comment by amicming** [comment]
the issue is  'this._initMediaController();' in the Connection constructor.  Everything work once that line is removed.

**Comment by marcogrcr** [comment]
Hi @amicming:

Keep in mind that `amazon-connect-streams` is now [published as an `npm` package](https://www.npmjs.com/package/amazon-connect-streams), so you should use the package if you're not doing it already.

Are you using `import "amazon-connect-streams";` or `<script src="amazon-connect-streams.js"></script>`? If you're using the first method, consider revising your bundler configuration, there may be something in there that's breaking it. Keep in mind that `amazon-connect-streams` is not implemented as a module, it relies on `this === window`.

Try using a barebones app to verify that it works, and slowly start adding your customization to see what breaks it. Although not for `angular`, here's a barebones `amazon-connect-chatjs` + `react` example that you can adapt to `amazon-connect-streams` + `angular`, and slowly add your customizations: https://github.com/amazon-connect/amazon-connect-chatjs/issues/10#issuecomment-639945642

Another thing you can do, is try to initialize the CCP version 2 rather than version 1, as I have seen some issues when using the old CCP (e.g. #263).

```js
// instead of /connect/ccp
ccpUrl: "https://instance-name.awsapps.com/connect/ccp-v2"
```

Additionally, if you're using the chat functionality, keep in mind that you'll also need to include [amazon-connect-chatjs](https://github.com/amazon-connect/amazon-connect-chatjs).

**Comment by amicming** [comment]
Thanks, @marcogrcr, for replying.  

Our Custom application works fine with 1.3, and we started upgrading with 1.4.8, and we initialized the CCP version 2. 

We're using as a `<script src="amazon-connect-streams.js"></script>`. 

`this.getMediaInfo()` - It is always returning undefined at this stage - https://github.com/amazon-connect/amazon-connect-streams/blob/master/release/connect-streams.js#L24112

**Comment by ctwomblyamzn** [comment]
Hi @amicming. I am assuming that this is happening for VoiceConnections, as you mentioned that it happens on calls in your original post. Is this happening for chats as well for you? I am not able to reproduce this issue with our latest release.

**Comment by ctwomblyamzn** [comment]
We are going to assume this issue was resolved. Please reopen an issue if this is still a problem.

**Comment by amicming** [comment]
@ctwomblyamzn , per our discussion, we commented out below code in `1.4.8` and working. 

```
Connection.prototype._initMediaController = function () {
    // if (this.getMediaInfo()) {
    //   console.log(`this.getMediaInfo() : ${JSON.parse(JSON.stringify(this.getMediaInfo()))}`);
    //   connect.core.mediaFactory.get(this).catch(function () { });
    // }
  }
```
Need to validate with latest version of stream api.

**Comment by sleethma** [comment]
This was closed a bit ago, but I'm experiencing same issue as @amicming in streams v2.3.2

Her commenting out suggestion still works, but seems a bit off to need to modify the streams lib.
