### ISSUE TITLE
Hang up on callback before connecting

### ISSUE THREAD

**Issue by JulianAyoub** [amazon-connect/amazon-connect-streams#291]
Hi my name is Julian,

I am trying to think of a way to allow agents to remove callbacks through a webpage connected to streams. I was wondering if there was any way to remove a callback with contact.destroy()?

Here is my plan, have agents enter a phone number into a text box. Upon pressing a button, an API is called and a field with that phone number is added into DynamoDB with the word "False". Now when an agent picks up a callback with this "False" field attached to it, instead of initiating the call, I was hoping something like contact.destroy() could remove this call from our system.

I am okay with implementation, what confuses me is the how to successfully clear the contact without actually calling the customer at all... Is this possible. Is there any other function I could call to have similar capabilities?

If anyone could help explain the functionality of contact.destroy() that would be great! Even if it can't do what I'm hoping...

contact.destroy({
   success: function() { /* ... */ },
   failure: function(err) { /* ... */ }
});

To anyone who responds to this I thank you for your time!
Regards,
Julian

**Comment by ctwomblyamzn** [comment]
Hi Julian, I am not sure whether you want to know how to reject the callback for a particular agent, or to clear the callback from the queue entirely. The latter behavior is not possible using `amazon-connect-streams` without "answering" the callback in some capacity, which will trigger a call to the customer. 

Unfortunately, contact.destroy is deprecated. We are going to update our documentation very soon to make this clear, as well as remove it entirely from the api. It will fail with an exception if you call it now anyway, so the behavior should not change much.

You should use connection.destroy() on the agent connection to reject an incoming contact, whether QCB or otherwise.
