### ISSUE TITLE
connect streams js can't load in Lightning Web Component

### ISSUE THREAD

**Issue by klthaw** [amazon-connect/amazon-connect-streams#301]
I am trying to load connect streams js file located in static resource.
But got **undefined** error.
If there any solution and best way to implement with LWC, please share. 
Thank in advance.

import { LightningElement } from 'lwc';
import { loadScript } from 'lightning/platformResourceLoader';
import connectStreams from '@salesforce/resourceUrl/connectStreams';

export default class Custom_ccp extends LightningElement {

    connectedCallback() {
        Promise.all([
            loadScript(this, connectStreams)
        ])
        .then(() => {
            alert('loaded');
        })
        .catch(error => {
            alert('error : ' + error);
        });
    } 
}

**Comment by intptr-t** [comment]
Maybe it can't because of "Lightning Locker Service" constraints.
There is no option to disable it after Summer'17.
https://developer.salesforce.com/docs/component-library/documentation/en/lwc/security_locker_service

// Maybe this constraint is why Amazon Connect CTI Adapter AppExchange is builted in Visualforce(?)

**Comment by h3adache** [comment]
Hi @klthaw I'm sorry but I think this is a question for the Lightning Web Component team.
We don't handle integration questions unless there's an issue in our component itself.
