### ISSUE TITLE
Set Agent to Offline via Connect API?

### ISSUE THREAD

**Issue by cgalway-ecs** [amazon-connect/amazon-connect-streams#302]
I notice this [issue](https://github.com/amazon-connect/amazon-connect-streams/issues/150) is stating that it is not possible to set an Agent's state to Online via the connect API, only via the Streams API, however I wish to do the reverse - setting all Agents to Offline
If you go to the real-time metrics page for agents (your-connect-instance.awsapps.com/connect/real-time-metrics?tableType=user), then you can set agent status for all agents to Offline from that page.
![image](https://user-images.githubusercontent.com/69194592/92234841-a3e89080-eeaa-11ea-8f06-b10fdb5749f5.png)
Does anyone know how I could replicate this in Node.js?

Here is what I have so far - I can get a list of Agents to iterate over, I just don't know how to set them to Offline like the aforementioned page can

```
var AWS = require('aws-sdk');

//console.log("Access key:", AWS.config.credentials.accessKeyId);
// var connect = new AWS.Connect({apiVersion: '2017-08-08'});
var connectClient = new AWS.Connect({
  apiVersion: "2017-08-08",
  region: "eu-central-1"
  });
const connectInstanceId = "<redacted>";
var listUsersParams = {
  InstanceId: connectInstanceId
};
GetUsers()
return

async function GetUsers(){
  // https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#listUsers-property
  var listUsersPromise = connectClient.listUsers(listUsersParams).promise();
  var listUsersResponse = await listUsersPromise;
  var list = listUsersResponse.UserSummaryList;
  list.forEach(element => {
    console.log(`Found user ${element.Username}`)
    // Here, I wish to set all agents to Offline
  })
}
```

**Comment by ctwomblyamzn** [comment]
Hi @cgalway-ecs, while this is "technically possible" using the endpoint visible by inspecting the network transaction that happens when you perform an agent state switch from the real time metrics -- agent page, we do not encourage you to utilize this as it is not a publicly documented api / endpoint, meaning that the team that manages this endpoint will not maintain it as if customers depend on it in a backwards compatible fashion. Therefore, this particular endpoint is "use-at-your-own-risk".
