### ISSUE TITLE
contactInfo.getQueueTimestamp() value always changed

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#323]
When we received the incoming call the contactInfo.getQueueTimestamp() value always showing local time. Always the getQueueTimestamp value will be changed.

**Reproduce the scenario:**

1. Make in coming call
2. Check the contact.getQueueTimestamp()
3. Dont accept the call and make it as missed call
4. Wait 2 or 3 seconds. Now clear the missed call state
5. Again will recive the incocming call
6. Now check the contact.getQueueTimestamp() . This will be modified.

We are unable to get the initial queue time stamp value from contact.getQueueTimestamp(). This value keep on changing .

Appreciate your help on resolving this.

**Comment by Christian-Sesta** [comment]
I have the same issue on my end and ideally I would have used this to calculate the contacts time in queue. Without this, there doesn't seem to be a good way to calculate this, and there also doesn't seem to be a relevant queue metric for this either within a contact flows`Set contact attributes` block.

**Comment by sivac47123** [comment]
Thanks @Christian-Sesta for your response.

**Comment by seiyako** [comment]
The contact.getQueueTimestamp() returns the timestamp of when the contact is routed to the queue. Unfortunately it's an expected behavior that the value is updated when the contact is re-routed to the queue, and Streams doesn't provide a way to retrieve the initial timestamp.
If you want to know how the contact behaved in the queue, Contact Search under Metrics and Quality tab in the admin panel should be helpful.
