### ISSUE TITLE
Windows notification 

### ISSUE THREAD

**Issue by KisungTae** [amazon-connect/amazon-connect-streams#370]
Hello Team,

Thank you very much for this amazing library.

I have a question regarding desktop (Windows 10) notification.
 
So, we are building a custom CCP page (HTML) that is hosted on S3 with this library.

When an incoming call comes in, users receive a notification from their desktop (Windows 10) which says 

```
Incoming Call +12 345 354 456
Click here to open the contact control panel now.
some-org.awsapp.com
```

When the users click on the notification, it takes them to the default AWS Connect CCP tab in Chrome browser which is usually accessed via the URL like https://some-org.awsapps.com/connect/ccp-v2/softphone

Can I make our custom CCP get the focus when users click on the desktop notification, please?

Our custom CCP page is just an HTML page with amazon-connect-1.6.3.js. It uses pre-built iframe and html has the script tag which contains custom functions.

So, I put the following code in contact.onConnecting() as I read [#93 ](https://github.com/amazon-connect/amazon-connect-streams/issues/93)

            connect.becomeMaster("NOTIFICATIONS")
            const incomingPhoneNumber = contact.getInitialConnection().getAddress().stripPhoneNumber();
            connect.ifMaster("NOTIFICATIONS", function () {
                const notificationManager = connect.core.getNotificationManager();
                notificationManager.show("Custom Notification 1111 Call from" + incomingPhoneNumber, {
                    body: "Custom Notification Click here to open the contact control panel now.",
                    clicked: function () {
                        window.focus();
                        this.close();
                    }
                });
            });
 

But no luck, users still see the default notification which takes them to the default AWS Connect CCP.

Is there a way to make our custom CCP get the focus when users click on the desktop notification, please?

Thanks and regards
Michael

**Comment by bkapellusch** [comment]
Michael,

  I was able to get a custom notification to work like this:
```
const incomingPhoneNumber = contact.getInitialConnection().getAddress().stripPhoneNumber();
const notificationManager = connect.core.getNotificationManager();
 notificationManager.show("Custom Notification 1111 Call from" + incomingPhoneNumber, {
      body: "Custom Notification Click here to open the contact control panel now.",
      clicked: function () {
          window.focus();
      }
 });
```
 
 I didn't do the ifmaster/becomemaster stuff, and left off the this.close() call.  
 
 I also had to do a call to connect.core.getNotificationManager().requestPermission() the first time so that Chrome would allow notifications from our custom CCP. 
 
 It doesn't however solve the problem of suppressing the original notification that comes from Amazon.  Maybe it's possible by replacing the _.showImpl function at runtime with a wrapped function that can ignore the original notification, but that seems like a pretty bad hack that could easily be broken.
 
 A better solution for that would be for Amazon to allow a flag to be passed in when initializing the CCP that would suppress that original message

**Comment by alexgurr** [comment]
@bkapellusch We've tried everything under the sun to get this disabled. Unfortunately your hack doesn't work as the CCP iframe has its own `window` and `connect-streams` code so you can't override them due to X origin. There's literally no way of surpressing them.
