### ISSUE TITLE
Using default system statuses for busy and missed

### ISSUE THREAD

**Issue by shaun0024** [amazon-connect/amazon-connect-streams#376]
Using the default CCP, when a contact is incoming, the status of the agent is 'PendingBusy' and when the agent has missed a contact, it is 'MissedCallAgent'. If building a custom CCP, instead of creating new statuses to represent each of these states, is it possible to reuse these system states? Using agent.getAgentStates(), I can only see 'Available', 'Offline' and other custom states that I have created.

**Comment by ctwomblyamzn** [comment]
Hi @shaun0024, our state terminology can certainly be confusing. The real issue here is that we need to differentiate agent system states from agent availability states. Agent availability states are returned by the `agent.getAgentStates()` api, while agent system states show up in the agent snapshot while on a call. Are you talking about the ccp accessible at `/ccp`, and not `/ccp-v2`, because if you observe our `/ccp-v2` app, you will see that we always display an agent availability state in the top left. If you wish to programmatically know the agent system state for voice calls, it is available through [`agent.getStatus`](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/api.js#L386). 

Let me know if that answered your question.

**Comment by shaun0024** [comment]
Hi @ctwomblyamzn,

Thanks for your reply. Let me try to illustrate this in the form of a scenario if I build a custom soft phone.

When a contact is coming through to an agent on a custom soft phone, I want to set the status of soft phone to a 'busy' status. In the default CCP, this state is called 'PendingBusy'. From the documentation, it seems like we need to get the state object using the agent.getAgentStates api and then use that with the agent.setState:
var state = agent.getAgentStates()[0];
agent.setState(state, {
   success: function() { /* ... */ },
   failure: function(err) { /* ... */ }
});

However, this 'PendingBusy' state is not available through either agent.getAgentStates, which will only show 'Available', 'Offline' and any other custom states created. Similarly, 'MissedCallAgent' is also not available.

So, not sure how we can get these two state objects (i.e. PendingBusy, MissedCallAgent) to use with agent.setState?

**Comment by ctwomblyamzn** [comment]
Ah, you are trying to put the agent into the 'PendingBusy' state.. That is not possible for the agent to do. Streams exposes apis relevant to agent actions and information. Agents can only change their availability state, which often mirrors their state. `agent.getAgentStates()` provides all eligible availability states.  

In order to change into the 'PendingBusy' state, you must be on a voice contact. Connect's system will change the agent into the 'PendingBusy' system state while on that contact at a certain point in the flow. As you point out, 'MissedCallAgent' is another system state that is not an availability state and as such, only Connect's system can propagate the agent into that state. In the case of 'MissedCallAgent', this state happens when the agent has not successfully accepted the contact within 20 seconds.

What are you trying to accomplish, in the big picture? If you simply want to reflect the current system state of the agent during a call on your custom CCP, use `agent.onStatusChange` to subscribe a callback that will change the visually displayed status on your custom CCP.

**Comment by shaun0024** [comment]
Basically, I'm trying to build a custom CCP that includes a other channels outside of Amazon Connect.

When a new contact comes in from this external channel, Amazon Connect would not know anything about it and there could potentially be a new Connect contact that gets routed to the agent at the same time. So I was hoping to be able to use automatically set the agent to this 'PendingBusy' state to prevent a new Connect contact from being routed at the same time. Right now, I have to create a custom status in Connect to basically act as this 'PendingBusy' state.

Similarly, if a contact from this external channel is missed, I was trying to set it to 'MissedCallAgent' but have also created another custom status to mirror this state. Also, because the 'MissedCallAgent' state can't be used, the metrics that come through for Connect for each agent when a call is missed would not take this external channel into consideration and I need to consolidate the results.

Anyway, no worries, was just hoping it was possible to simplify things. Thanks @ctwomblyamzn.

**Comment by ctwomblyamzn** [comment]
I'm not sure why you need to use the reserved `PendingBusy` state to ensure agents are not routed contacts... any custom state will do that, as you point out. You can make the custom state specific to your custom media channel even. 

Unfortunately in the case of `MissedCallAgent` and connect metrics, we cannot provide metrics for custom, third party states right now. So yes, its not possible to have connect generate metrics at this time for your custom channel. 

I'm going to close this issue as it looks like your questions were answered. Please reopen if you have further queries.
