### ISSUE TITLE
amazon-connect-1.3.js upgrade available ?

### ISSUE THREAD

**Issue by darwinanirudh** [amazon-connect/amazon-connect-streams#406]
Hello Team .,

I am currently using amazon-connect-1.3.js . Is it possible I can get the upgraded and latest version something like **amazon-connect-1.6.js**

**Comment by altesean** [comment]
You can manually download the latest from the release page linked on the main page of the project, follow the instructions in the readme to migrate your code to use NPM to manage your package version (this is probably what you should do, it was not packaged to NPM in the 1.3 era which is why your predecessor did not use the NPM package.) or even check out the code locally and compile it yourself (by your question this might be outside your comfort zone... but is a option).

**Comment by yaminli-aws** [comment]
Thanks @altesean. Hi @darwinanirudh please check @altesean comment above, which is also what we recommend for customers.
