### ISSUE TITLE
'clearContact' API request failed: Error

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#422]
I'm trying to handle a contact that's in **ENDED** state, with `contact.clear()`.

However when I do this, I get ```'clearContact' API request failed: Error```?

I've also tried `complete()` to no avail. Any ideas?

**Comment by martin-greenberg** [comment]
It's not possible to investigate further without more log context on this besides just the string "Error". This sounds more like a backend API failure rather than an issue in Streams itself, so you may want to open an AWS support request if possible instead of trying to get help with this issue on GH.
