### ISSUE TITLE
CCP refused to connect

### ISSUE THREAD

**Issue by sachinjabshetty** [amazon-connect/amazon-connect-streams#435]
Hi I am testing the screen pop up ccp stream api and hosted html and js file on the S3 bucket. Added link in the connect add origin.
 when we trying to access we are getting the login screen but once we login its takes to dashboard not the ccp also, the main window says "instance-name.awsapps.com refused to connect. screen shot attached.

I am very new to the coding. Please help me here.

![error](https://user-images.githubusercontent.com/86469612/123516800-8eec2080-d6bb-11eb-8565-d83c815e148d.PNG)

**Comment by SamSchiff** [comment]
Hi, thanks for the question. We should be able to help but we'll need some more info. Can you detail how you're attempting to login? I'm most curious about your initCCP configuration, but the more you can tell us the better. Also, if you can check the console logs in the browser upon attempting to login that would be helpful. Lastly, I just want to confirm that your connect instance authenticated through Connect, rather than through SAML. I inferred that from your question but let me know if I'm incorrect

**Comment by SamSchiff** [comment]
No response, closing for now
