### ISSUE TITLE
CCP Not Successfully Logged In

### ISSUE THREAD

**Issue by ebony-g** [amazon-connect/amazon-connect-streams#450]
Hi,

I am having issue logging in to my CCP, the scenario is, the connect log in window shows up, user account is validated and redirects to connect home using the same window but the user is not successfully logged in/online to Connect. May I know what I've missed?

Just follow the default initCCP by only changing the correct URL
{
      ccpUrl: "xxx/ccp-v2/",
      region: "xxxx",
      loginPopup: true,
      loginPopupAutoClose: true,
      softphone: {
        allowFramedSoftphone: true,
      },
    }

Thank you.

Regards,
Ebony

**Comment by ctwomblyamzn** [comment]
"user account is validated and redirects to connect home using the same window but the user is not successfully logged in". Hmm? What do you mean by "successfully logged in"? What signal are you using to indicate that a user is successfully logged in if not being federated into a Connect site past the login page?

If you mean that in metrics you're not seeing that the agent is online, that could be because the agent is in the Offline state.
