### ISSUE TITLE
“X-Frame-Options“ directive set to “SAMEORIGIN“.

### ISSUE THREAD

**Issue by rneralla-equinix** [amazon-connect/amazon-connect-streams#483]
Hello,
I am, facing this "“X-Frame-Options“ directive set to “SAMEORIGIN“ error in loop after Authentication.  and this is happening in Firefox,
Can any one please guide me the on this to fix.

Thanks

**Comment by h3adache** [comment]
Can you provide more details on your use case? If this is coming from CCP then it can be rectified by adding allowed origins as mentioned by @marktheunissen.

**Comment by PabloApser** [comment]
@rneralla-equinix Hi, can you explain how do you fix this problem? I´m trying to do the same and only receive the error: "Refused to display 'https://XXXXXXX.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

I have the "content-security-policy" in an angular app configure with:
```
content-security-policy: "default-src 'self'; frame-src 'self' https://xxxxxxxxxxx.my.connect.aws https://xxxxxxxx.awsapps.com  data:; 
```

**Comment by laisiulong** [comment]
@PabloApser I faced the same issue when Chrome/Edge can display Embedded CCP correctly but Xframe problem with Firefox. One of the reason is due to Firefox Enhanced Tracking. You could try to disable it for your domain to see any luck. It worked with my case
https://www.youtube.com/watch?v=TBNnGyOScAI&feature=youtu.be
