### ISSUE TITLE
Login popup doesn't appear

### ISSUE THREAD

**Issue by evanlarkin10** [amazon-connect/amazon-connect-streams#490]
I'm not using the built in interface but instead building one from scratch and I am having a lot of trouble getting the authentication flow to work. It gets caught in this state where I am not authenticated and the popup doesn't appear. It detects authentication if I am logged into a connect instance in another tab. If I am not logged in the popup rarely displays, or if I log out of the other tab and refresh it doesn't popup. 

When it is in this state, there is a looping of calls happening every few seconds to https://<myinstance>.my.connect.aws/connect/login and https://<myinstance>.my.connect.aws/login
![output](https://user-images.githubusercontent.com/36309287/138281597-bc8b5f5d-77e5-4b05-b28a-7ffea371abac.png)

**Comment by WangBank** [comment]
you can use local storage clear, it will help you

**Comment by marktheunissen** [comment]
Hi, we just ran into this too. The problem seems to be the following mechanism in Streams:

```js
connect.PopupManager.prototype.open = function (url, name, options) {
  var then = this._getLastOpenedTimestamp(name);
  var now = new Date().getTime();
  var win = null;
  if (now - then > ONE_DAY_MILLIS) {
```

https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/util.js#L517

If the user **has** triggered the login popup in the last 24 hours, and the user **hasn't** set a loginUrl, then the Streams lib will not open the login popup no matter what you do. The only workaround is to wait 24 hours, or login using the CCP-V2 directly, or clear your localStorage. 

```js
// clear out last opened timestamp for SAML authentication when there is ACK_TIMEOUT
if (params.loginUrl) {
  connect.core.getPopupManager().clear(connect.MasterTopics.LOGIN_POPUP);
}
```

https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/core.js#L878-L881

This seems to be a bug in Streams SDK since it's pretty easy to get into this state. 

There is an additional clearing of the timestamp in localStorage which happens here on `ACKNOWLEDGE` from the shared worker: https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/core.js#L893-L902, but this is subject to race conditions and timing errors - if the JavaScript execution is killed with bad timing, the browser can get into a situation where it will "lock out" the agent from getting back.

1. Why is there a 24 hour lockout period for the popup window?
2. Could this entire system be reworked to be more resilient to failures?
3. If not, perhaps there are other circumstances where clearing the timestamp in localStorage would be good. For example, it would be a good idea to clear it when refreshing the browser. Even choosing sessionStorage might be better.
