### ISSUE TITLE
Amazon Connect Logout + Agent Status

### ISSUE THREAD

**Issue by tylerlot** [amazon-connect/amazon-connect-streams#493]
Hi,

The docs suggest hitting `/logout` route to sign a user out of connect when using a custom CCP. I have validated that after hitting this route, if I try to access/refresh the CCP it shows my session has expired, however, the agent's status does not update be offline. I confirmed this behavior by opening the ccp in one tab, then logging out by opening a new tab directly to the logout route. The agent's CCP status never changes, and upon the next sign-in they are in their previous status (for example after contact or available). I was wondering if it is expected that logging an agent out won't move their status automatically to offline?

**Comment by tylerlot** [comment]
Note, the agent state appears to be properly set when we hit the CCP's "log out" button

**Comment by mschersten** [comment]
I do not believe that the CCP logout button, or any other logout method, should be setting agents to offline automatically.  Generally there are two distinct issues here, agent status and "logged in" status, and they are separate.  We allow agents to login, set themselves to a non-routable status and then log out and remain in that status.  We do have custom logic in the application logout flow and using onbeforeunload to check if the agent is available and set them to a non-routable status if they are, in order to prevent agents from receiving calls when they are not logged in or have closed the tab.

**Comment by tylerlot** [comment]
Is there any consideration for making this enhancement? What you just described above is that you are actively avoiding having an agent in a routable state when they are no longer logged in - yet the system itself, when you are no longer logged in, makes no effort to also do this for any client who implements their own CCP. It would be a better end user experience for logouts themselves to also manage these updates.

**Comment by tylerlot** [comment]
Any update on this issue or potential for the enhancement? I am still quite lost on how it is a desirable behavior to have an agent who has logged out of the system to remain in a routable state? Your CCP application itself does this manual setting to offline on logout, I don't understand why hitting the /logout route would not do this for users to keep their statuses "in sync"

**Comment by ctwomblyamzn** [comment]
Hi @tylerlot we agree that it is not desirable to have an agent who is logged out in a routable state. I will note that after an agent receives one contact, and misses it (because they are logged out and not on CCP), that agent will not be routed any more contacts until they clear the current missed contact. However, it would be more ideal if that were immediate, and did not necessitate a missed contact to occur. We are working on addressing this, but it is a longer term fix.

**Comment by tylerlot** [comment]
Thanks for the update @ctwomblyamzn! Any context into a tentative expected rollout date for that change? Will it require any client side updates (i.e. new SDK version vended), or will all of this be managed from backend updates?

**Comment by ctwomblyamzn** [comment]
The current idea is that it will be managed from the backend, no client-side updates.

**Comment by lwang-79** [comment]
Hi @ctwomblyamzn, is there any update for this enhancement?
