### ISSUE TITLE
UpdateContactAttribute

### ISSUE THREAD

**Issue by ronelCS** [amazon-connect/amazon-connect-streams#566]
Hi, can anyone help me here to figure out here. Im using AWS CCP with cuztomize disposition to edit/update the contact flow attribute. I think it didnt went through or its not working on my side.

can anyone help me? or give advise.

This is what i found for UpdateContactAttribute : https://docs.aws.amazon.com/connect/latest/APIReference/connect-api.pdf#Welcome

![SampleCodeAttribute](https://user-images.githubusercontent.com/98431635/165855530-05754996-d6a8-4f63-8951-44fa3a9e0a83.PNG)

The error i am getting.

![samplerror](https://user-images.githubusercontent.com/98431635/165855720-1caf4e9f-8d94-4298-8e66-79d950d6c7f2.PNG)

**Comment by ana-vf** [comment]
hey @ronelCS this is because you are trying to use an SDK method
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#updateContactAttributes-property 
and it is not available in streams (unfortunately) where you get only get / read them
https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactgetattributes

so a solution would be to update these attributes from a lambda where your front end app can send a payload - for example.

streams would then have them available on next refresh

**Comment by vpogudina** [comment]
Seems that ana-vf has provided you an answer and a solution. Please feel free to reopen issue if you have follow-up questions.
