### ISSUE TITLE
Amazon Connect login page can't authenticate if opened from a sandboxed iframe without 'allow-top-navigation' or 'allow-top-navigation-by-user-activation'

### ISSUE THREAD

**Issue by ctunna** [amazon-connect/amazon-connect-streams#568]
I have a streams integration that is running in an iframe sandbox I have no control over.  This integration launches the Amazon Connect login page in a popup window.  When users enter their credentials the login page attempts to perform a client side redirect back to Amazon Connect but this fails as its not permitted by the iframe sandbox. 

Looking for guidance on how to proceed or work around this issue.  Shouldn't AC be performing this redirect on HTTP headers?

Please see attached image

![edit](https://user-images.githubusercontent.com/3189763/167872740-ef8e7ea8-8c3d-4d8e-b9b1-6026d180dba1.png)

**Comment by edvilme** [comment]
Are you testing from localhost? Did you whitelist the domain and port?

**Comment by ctunna** [comment]
Thanks for your response.  Yes the origin has been added to the allow list.  The streams API performs as expected if we login from outside of a sandboxed iframe.

**Comment by peckjj** [comment]
Hi Connect Team!

We are experiencing a similar issue. All domains involved in displaying the Amazon Connect UI have been whitelisted inside of AWS.

Here's a snippet from our project:
```
connect.core.initCCP(this.containerDiv, {
        ccpUrl: ccpUrl,
        region: 'us-east-1',
        loginPopup: false,
        loginPopupAutoClose: true,
        softphone: {
          allowFramedSoftphone: true,
          disableRingtone: false
        }
      });

const loginPopup = window.open(ccpUrl, connect.MasterTopics.LOGIN_POPUP);

getEventBus().subscribe(connect.EventType.ACKNOWLEDGE, () => {
        loginPopup.close();
      });

function getEventBus() {
    return connect.core.getEventBus();
  };
```

After executing the code, we successfully open a login popup in a **new tab**, but after a successful login we see the same 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' error cited in the post within the console of the login tab. As a result, the login popup hangs, never closes, and the ACKNOWLEDGE event never comes through the event bus.

We have seen that this issue is not consistent, and we have not narrowed it down do any specific browser or environment. It works on some machines 100% of the time, and the login popup closes as expected, and on other machines it fails almost 100% of the time. (Using Chrome and Edge on all machines tested). 

The current workaround we have identified is to open the login page separately and perform a login before accessing and loading our tool. Now the login **popup** will detect that we are already logged in, will not display a login form, and immediately close as we handle the event bus event.


What could be the cause of this? Please let me know as soon as possible that this comment was acknowledged and if there is any more information I can provide!
