### ISSUE TITLE
Agent can't save audio settings until they click the Language dropdown.

### ISSUE THREAD

**Issue by codermpl** [amazon-connect/amazon-connect-streams#596]
We set enableAudioDeviceSettings to true so agents can select their audio devices. When the agent selects their audio device, the Save button remains greyed out. They have to click the language dropdown to get the Save to be enabled. This is confusing to agents and we get many agents can't figure out how to save their audio device settings.

The agent should be able to save when they select an audio device setting. Web Browser is Chrome

CCP settings
```
        const initCcpProps = {
          softphone: {
            allowFramedSoftphone: true,
          },
          pageOptions: {
            enableAudioDeviceSettings: true,
          },
        };
```

**Comment by codermpl** [comment]
I looked through the code and it looks like there is a recent code change that's supposed to fix this. What version of amazon-connect-streams do we need to get the fix?

**Comment by seiyako** [comment]
Currently audio device settings is applied as soon as you select an item in the dropdown. Save button doesn't actually have any effects (though we fix the Save button behavior to mitigate the confusions). 

Audio device settings for the speaker/ringer devices are not available in CCP UI because Firefox browser has a limitation that mediaDervices.enumerateDevices() doesn't return output devices unless a pref flag is set. ([src](https://bugzilla.mozilla.org/show_bug.cgi?id=1152401))
