### ISSUE TITLE
X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by jlopez0313** [amazon-connect/amazon-connect-streams#605]
Hi everyone!

I followed the init config, and now, when i run the app, i'm getting this error:
`Refused to display 'https://MY-INSTANCE.my.connect.aws/' in a frame because it set 'X-Frame-Options' to 'sameorigin'. `
How can me fix it? i already added localhost and 127.0.0.1 to approved origins and nothing changed...

**Comment by m66rus** [comment]
I had this a while back and drove me mad as I had added the origins etc but there was something wrong with my cloudfront config so I recreated it and solve the issue.If you are not using CF then check you S3 bucket policyOn 31 Oct 2022, at 23:47, Jonathan López Londoño ***@***.***> wrote:﻿
Hi everyone!
I followed the init config, and now, when i run the app, i'm getting this error:
Refused to display 'https://MY-INSTANCE.my.connect.aws/' in a frame because it set 'X-Frame-Options' to 'sameorigin'. 
How can me fix it? i already added localhost and 127.0.0.1 to approved origins and nothing changed...

**Comment by fezekilePlaatyiAbsa** [comment]
@jlopez0313 did you manage to solve this issue? I am having the same issue

**Comment by jagadeeshaby** [comment]
if you have already allowlisted the domain, it could be that you are not logged in to your connect instance.

could you try login into connect instance first ( just by loading connect url in a new tab and login) then access the app in a embedded mode? if that works make sure you configure loginPopup option to true. 

please let me know if that helps
