### ISSUE TITLE
How to solve the X-frame options to sameorigin error even when added my domain in the Approved domains?

### ISSUE THREAD

**Issue by fezekilePlaatyiAbsa** [amazon-connect/amazon-connect-streams#631]
I get the error: Refused to display 'https://<instance-id>.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin' while I have added the domain under approved domains? Its confusing because all the solutions I have seen(well they talk mainly about adding my origin onto approved origins) but that still doesn't work. My code for initiating this is as below:-

`

    const ccpUrl = "https://<instance-id>.my.connect.aws/connect/ccp-v2";
    window.connect.core.initCCP(document.getElementById(ccpContainerId), {
      ccpUrl: ccpUrl, // REQUIRED
      loginPopup: false, // optional, defaults to `true`
      loginOptions: {
        // optional, if provided opens login in new window
        autoClose: true, // optional, defaults to `false`
        height: 600, // optional, defaults to 578
        width: 400, // optional, defaults to 433
        top: 0, // optional, defaults to 0
        left: 0, // optional, defaults to 0
      },
    });

`

Please help.

**Comment by m66rus** [comment]
I had the same a while ago, I think the issue was with config on cloud front perhaps recreate itOn 21 Jan 2023, at 08:40, fezekilePlaatyiAbsa ***@***.***> wrote:﻿
I get the error: Refused to display 'https://.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin' while I have added the domain under approved domains? Its confusing because all the solutions I have seen(well they talk mainly about adding my origin onto approved origins) but that still doesn't work. My code for initiating this is as below:-
`const ccpUrl = "https://.my.connect.aws/connect/ccp-v2";
//----------------Init CCP Start----------------------------
try {
window.connect.core.initCCP(document.getElementById(ccpContainerId), {
ccpUrl: ccpUrl, // REQUIRED
loginPopup: false, // optional, defaults to true
loginOptions: {
// optional, if provided opens login in new window
autoClose: true, // optional, defaults to false
height: 600, // optional, defaults to 578
width: 400, // optional, defaults to 433
top: 0, // optional, defaults to 0
left: 0, // optional, defaults to 0
},
  // region: connectRegion, // REQUIRED for `CHAT`, optional otherwise
  softphone: {
    // optional, defaults below apply if not provided
    allowFramedSoftphone: true, // optional, defaults to false
    disableRingtone: false, // optional, defaults to false
    ringtoneUrl: "./ringtone.mp3", // optional, defaults to CCP’s default ringtone if a falsy value is set
  },
  pageOptions: {
    // optional
    enableAudioDeviceSettings: true, // optional, defaults to 'false'
    enablePhoneTypeSettings: true, // optional, defaults to 'true'
  },
  ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
  ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
  ccpLoadTimeout: 10000, //optional, defaults to 5000 (ms)
});
connect.getLog().warn("CDEBUG >> CCP initialized");

} catch (err) {
console.error(err);
}
//--------`
Please help.

**Comment by fezekilePlaatyiAbsa** [comment]
@m66rus recreating the AWS Connect instance is that what you mean?

**Comment by m66rus** [comment]
No, are you using Cloudfront to point to your S3 Website?

**Comment by fezekilePlaatyiAbsa** [comment]
No I using just normally website hosting on S3 with http:// 
But this also doesn't work on localmachine on http://127.0.0.1:5501 while I added http://127.0.0.1:5501 as approved domain

**Comment by thtliife** [comment]
> No I using just normally website hosting on S3 with http:// But this also doesn't work on localmachine on http://127.0.0.1:5501 while I added http://127.0.0.1:5501 as approved domain

@fezekilePlaatyiAbsa, i've never been able to get a `http://` origin to work... i have always needed to use `https://` (possibly due to websockets requiring wss protocol?)

Anyways.. i just generated a self-signed cert, and serve my local dev stuff off `https://localhost:4443` or similar (any port will do)

**Comment by kevinhooke** [comment]
Just to confirm that http does work, we load our app from http://localhost:3000 and with that url added in 'Approved Origins' it does work as expected.

**Comment by fezekilePlaatyiAbsa** [comment]
> Just to confirm that http does work, we load our app in dev from http://localhost:3000 and with that url added in 'Approved Origins' it does work as expected.

@kevinhooke thanks for this. I can also confirm we later discovered it was some firewal issues that made loading not to work on localhost. Thanks
