### ISSUE TITLE
Pass attributes or parameters when do an outbound call 

### ISSUE THREAD

**Issue by jonatandmapser** [amazon-connect/amazon-connect-streams#643]
Hi,

Is there the option pass attributes or parameters when do an outbound call (agent.connect(..)...), so I can read them on the Contact Flow?

The scenario is the following:
I have a multi-brand environment. On CCP before calling the customer the agent has to select the country and brand.
Then on the Contact Flow I will set them as Contact Attributes for statistical reasons and I will also set the outgoing caller Id (using Lambda & DynamoDB)

thank you in advance!

**Comment by jagadeeshaby** [comment]
As of Feb, 2023 Streams doesn't support setting Contact attributes on `agent.connect(..)...)` API.   

i do see that corresponding AWS Connect Public API support setting attributes, see if that's an option you could use here instead of using Streams API - https://docs.aws.amazon.com/connect/latest/APIReference/API_StartOutboundVoiceContact.html

This seems like a feature parity miss on Streams, will take this up for prioritization and put it in our 2023 backlog.

**Comment by asharma99** [comment]
@jagadeeshaby Is this Resolved or its requested as an enhancement, any idea when this will be available ?
