### ISSUE TITLE
new participant being added to multiparty call cannot see quick connect names originally in the call

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#701]
repro:
- agent 1 answers incoming call
- agent 1 calls agent 2 -> agent 1 will see "agent 2" quick connect name appear on screen. agent 2 will just see "INTERNAL-TRANSFER" for agent 1s name. In the code (agent 2 perspective):
```ts
const agent1Connection = contact().getConnections()[1];
const quickConnectName = agent1Connection.getQuickConnectName(); // -> will return undefined
```

To add to this, at this point if agent 1 were to add agent 3. both agent 1 and agent 2 will see "agent 3" on their screen. so at this point each agent sees the following:
#### Agent 1
- 123-222-2233
- Agent 2
- Agent 3

#### Agent 2
- 123-222-2233
- INTERNAL-TRANSFER
- Agent 3

#### Agent 3
- 123-222-2233
- INTERNAL-TRANSFER
- INTERNAL-TRANSFER

so the pattern seems to be "an agent can only see quick connect name for connections added while they were on the call".

But...why is this? Shouldn't every agent be able to see every other agents name in multiparty mode? The docs explicitly call this out as a MP feature:

> An agent sees the quick connect ID for other agents, instead of just internal transfer. [see](https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-release-notes.html#comparison-multi-party)

**Comment by tannera926** [comment]
Agents that are added through quick connects will have a name in the quick connect field. Agent 2 and Agent 3 were added as quick connects, so only their connections will have a quick connect name associated with them. When I reproduced this, Agent 2's name was visible for agent 3 as well, which follows this pattern.

**Comment by gjesse** [comment]
I do see that the replication steps have changed a bit for this in that agent 3 now sees agent 2's name. HOWEVER, closing this issue misses the point, which is at no point in any of this should INTERNAL-TRANSFER be shown for any agent. Certainly having 'INTERNAL-TRANSFER' as the quick connect name for the initial agent isn't accurate. is there another field where Agent 1's name can be accessed so that all agents can have a full picture of the call.

**Comment by gjesse** [comment]
Just to reiterate.. if this ticket is working as designed then the docs are misleading at best - https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-release-notes.html#comparison-multi-party

In Non multiparty mode: An agent only sees internal transfer for another agent on the call.
in Multiparty: An agent sees the quick connect ID for other agents, instead of just internal transfer.

So it's true that an agent now sees quick connect IDs for agents who were quick connected, we still see internal transfer for the original agent.
