### ISSUE TITLE
Ending a chat from agent's side...

### ISSUE THREAD

**Issue by peurman** [amazon-connect/amazon-connect-streams#732]
Hi. I need to ask you for the recommended way of **ending a chat** from agent's side.  

Clicking an 'end' button executes _handleEndSession_ function.

The code actually works, but I had to try different alternatives until I found this one that works:

```
const handleEndSession = async () => {
      if (chatsContacts[contactId]) {
        const { contact, connection} = chatsContacts[contactId]
        try {
          await connection.destroy()
         
          await contact.onEnded(() => contact.clear())  // ! console shows some API error but it works
         // dispatching some action...
        } catch (e) {
          console.log('Error when destroying connection session:', e)
        }
      } else {
        alert('No active chat connection selected')
      }
    } else {
      alert('No active chat selected')
    }
    // dispatching some other action...
  }
```

- Case I: using  **await cnn.destroy()** followed with **await contact.clear())** didn't work (even adding this last line in a finally{} block), because there was a delay to confirm the destroy of the connection, so a first click on the 'End Session' button was not clearing the chat.

- Case II: To probed theory of the delay, I wrapped the **contact.clear())** inside a SetTimeout with an interval greater than 400ms, and it worked.
- Case III:  I changed that SetTimeout with the code above and also worked, but now with this error in console: 'clearContact' API request failed.

Can you suggest me please the right way to do it?
Thanks!

**Comment by seiyako** [comment]
Hi thanks for reaching out.
To end a live contact, yes you should first call `agentConnection.destroy()` API which will disconnect the agent from the contact and put in ACW state. As you mentioned there’s async process in the background to update the agent/contact state and your next `contact.clear()` API call may fail if you call it too early (your Case I). The recommended way to detect the contact state turning to ACW state is using `contact.onACW()` API. See my example code snippet below:

```
// at contact initialization, register a callback to clear the contact that has turned ACW state
connect.contact((contact) => {
  contact.onACW((_contact) => {
    _contact.clear();
  });
});

// somewhere in other function, call destroy API when agent clicks end chat button
agentConnection.destroy();
```

You could do it with `contact.onEnded()` API, but for a historical reason the ENDED event is triggered twice at when a contact turns ACW state and when a contact is cleared, thus contact.clear() can be called twice and hence you’ll get a failure at the second invocation because the contact has already been cleared at the moment (your Case III).

**Comment by peurman** [comment]
Thank you so much @seiyako, I'll try that!
