### ISSUE TITLE
Agent Mute/Unmute issue during conference call

### ISSUE THREAD

**Issue by MHamza8070** [amazon-connect/amazon-connect-streams#820]
I am using Amazon Connect Streams latest version, during conference call multiple unmute agent events received when agent put on mute, after few seconds multiple unmute events in agent coming and agent automatically goes into unmute. This happens during conference call and it happens frequently please check this as mute unmute is very important functionality.
This event triggers the unmute events multiple times.
 agent.onMuteToggle(this.handleMutetoggle.bind(this));

`This is how I am muting and unmuting agents.
 async muteContact() {
    /**
     * PUTs agent on mute
     * also there is callback
     */
    await this.loggedInAgent.mute();
    this.logger.logInfoMsg("Agent muted via Streams");
  }
  async unMuteContact() {
    /**
     * Unmute agent
     */
    await this.loggedInAgent.unmute();
    this.logger.logInfoMsg("Agent unmuted via Streams");
  }`

**Comment by andywang219** [comment]
Hi,

Could you modify your logic to match this example: https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md#mute-agent ? The mute and unmute logic works differently when the agents are in a multiparty conference call.

**Comment by MHamza8070** [comment]
Hi @andywang219, I tried this method too but same behavior, agent getting multiple unmute events after initiating the mute action.

**Comment by andywang219** [comment]
Got it, you should use the sample code provided above because in a conference call, the mute/ unmute logic takes a different code path. That is why we need to use `muteParticipant` and `unmuteParticipant`. If you use `agent.mute()` or `agent.unmute()` during a conference call, then you will see the mute status being reverted.

Could you make sure that when the agents are in a conference call and you use the sample code above, that it is in fact calling `muteParticipant` and `unmuteParticipant`? You can add some console.logs to confirm which API is being used.

Also, do you have the enhanced monitoring/ multiparty enabled in your instance?

**Comment by MHamza8070** [comment]
Hi @andywang219  thanks for update, Yes monitoring/multiparty is enabled, okay I will try the above mentioned steps and will update then.

**Comment by MHamza8070** [comment]
Its working now I guess, I did initial testing and looks like its working, I will do further testing and let you know if face any issue, thank you @andywang219 for the guidance.

**Comment by MHamza8070** [comment]
Its working now I guess, I did initial testing and looks like its working, I will do further testing and let you know if face any issue, thank you @andywang219 for the guidance.
