### ISSUE TITLE
Mute button not working within embedded CCP

### ISSUE THREAD

**Issue by phill99** [amazon-connect/amazon-connect-streams#831]
We are facing an issue with the CCP v2 embedded into a CRM platform.

The settings we use with initccp are:
ccpUrl: url,
loginPopup: false,
region: "eu-west-2",
softphone: {
    allowFramedSoftphone: true,
    disableRingtone: false
}

This is not consistently reproducible, and works for some agents, but has been seen occurring on Edge.

**Comment by hngan** [comment]
Hey, can I get some more details as to what you guys mean by the mute button is not working? Are you claiming that pressing the mute button IN THE CCP (NOT USING STREAMS FUNCTIONS) is not actually muting the mic? Or are you claiming that the mute button is greyed out/disabled in the CCP. If the button is greyed out, this is by design as it means that in that specific tab, that CCP does not have media controls, and typically it means you have multiple CCPs opened where only one of them would have permissions to control the media.
