### ISSUE TITLE
Embedded CCP seems send toogleMute Event when Windows Lost Focus and prevent Mute

### ISSUE THREAD

**Issue by gierig1977** [amazon-connect/amazon-connect-streams#857]
ENV:
Chrome (WIN / MAC, latest and test some older)
Connect Instance with NOT "Enable Multi-Party Calls and Enhanced Monitoring"
Streams Version 2.4.5 and now 2.14 (latest)

ISSUE:
Agent set a call to Hold, Script than Mute to Prevent Voice Recordings from Agent side during on Hold
(if IsOnHold than agent.mute() else agent.unmute() to say it simple)
That work fine till around end of February, look al was fine bevor 23th of February.

Since than from the to time and 99% if the CCCP Windows lost focus (switch to another Application / website)
Mute Status toggle back to Unmute for no reason.
I can see that without any Logic a „ToggleMute" Event was triggered.

<img width="1327" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/131958743/87d294a9-a5a1-4aca-b63f-2b7da2335cd9">

(source seems the Embedded CCP Steams Version)

Also i see lots of 

<img width="1314" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/131958743/e679beaa-b258-436a-ab03-7d02b8fcea02">
With may should not happen if "Multi-Party Calls and Enhanced Monitoring“ is turned of ( and a single call even)

Look like the Embedded CCP is not happy to put a call on Mute and Unmute it after a few seconds.
(fit to the contact.onRefresh time)

Actual Workaround for me:
set a Flag and force during contact.onRefresh mute again if the call still on Hold, but that is ugly and dirty.

**Comment by andywang219** [comment]
Hi @gierig1977,

With the release of Google Chrome's [Storage Partitioning](https://developers.google.com/privacy-sandbox/3pcd/storage-partitioning) feature, the mute functionality was broken if users has CCP opened in two different top-level sites (ie. an embedded and a native). When an user has CCP opened in two top-level site, the user would only be able to mute themself in one of the CCPs, the one hosting the RTC session. As a short term solution, we disabled the mute button in the CCP that wasn't hosting the RTC session.

As a long term fix, we migrated the mute functionality to server coordinated mute. What this does is sync the mute state of every opened CCP via the backend. However to do this, we had to disable the mute functionality when the call is on hold or else the API will fail, as you can see in your screenshot. You mentioned that `muteToggle` was triggered without any logic. This is because when you tried to mute the call while on hold, the local mute state updates to "muted", but the backend did not because the API failed. So on the next `onRefresh` event, it will refer to the backend's state and update the local state to match the backend's state.

As a work around, you can call the mute API prior to placing the call on hold. It looks like for your use case, you want to mute the agent every time the agent places the call on hold. So before calling `connection.hold()` [code ref](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionmuteparticipant), you can first call `muteParticipant()` [code ref](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionmuteparticipant)

**Comment by gierig1977** [comment]
Hi @andywang219,
Thanks sharing that details, very helpful to understood the behaviour.

Agent using the embedded CCP in the Iframe as main CCP, we just add some
extras via the Stream-LIB (like better Agent Status, Active Queue, Routing Profile , some  call Attributes,
better logout handling and so on) 
So normally he will hit the HOLD button in the embedded CCP, that is why we than 
just check if a call on hold and mute it. To keep it Simple for the Agent.

Is there any Timeframe when the longterm fix will ne in place (like 4 Week or scheduled  in 5 Month)

I will Start next week to play around with the „new“ muteParticipant() function and may add a 
„you have to use it“ button that MUTE and than Hold the call than as workaround.

**Comment by andywang219** [comment]
Hi @gierig1977,

We are targeting August 2024 to deploy a change that would allow muting while on hold.

**Comment by vvgoyal** [comment]
Hi @gierig1977 

Please let us know if you have any questions.
