### ISSUE TITLE
[issue] Popping up the Amazon Connect login screen in the connect.core.initCCP() function

### ISSUE THREAD

**Issue by kimhanmiru** [amazon-connect/amazon-connect-streams#858]
I'm using connect.core.initCCP() to pop up the Amazon connect login screen, but when I don't log in from the popup screen and refresh the browser, the Amazon connect login screen should pop up again, but it doesn't pop up unless I clear my browser cookies or cache. 

We would like to know why.

**Comment by tannera926** [comment]
The reason is because there is currently no communication between the popup and the embedded CCP. We set a value loginPopup in localStorage when we open the popup and we remove that value when we close the popup (which is once the user is authenticated). If the page is refreshed, we see that the value for loginPopup is still in localStorage, so we don't open up the popup window again.

We are actively working on a fix for this.

**Comment by bretticus-mc** [comment]
I have a change ready to disable the local storage check so the functionality is the same as when loginUrl is defined. Looking to push it out this week. Working on an unrelated change as part of the release.

**Comment by bretticus-mc** [comment]
Fix with Streams version 2.14.1.
