### ISSUE TITLE
Listen in on conversations between agent and customer

### ISSUE THREAD

**Issue by pushkal-symsoft** [amazon-connect/amazon-connect-streams#880]
Is there an easy way to listen in on chat conversation between agent and customer? 

I was able to do it by modifying this function "connect.core.getUpstream().onUpstream(connect.WebSocketEvents.ALL_MESSAGE, function)" within connect-streams.js.

Even though it works in my custom application, this is causing issues when embedding my application as a 3rd party application within agent workspace. I think the connect-streams.js from CCP is conflicting with connect-streams.js in my custom application.

So I was wondering if there is an easier and cleaner way to do this.

**Comment by andywang219** [comment]
There is a feature that allows admins to monitor chats: https://docs.aws.amazon.com/connect/latest/adminguide/monitor-conversations.html.

However your custom application is not working when embedding it as a 3rd party app within agent workspace because 3P apps cannot initialize Streams in agent workspace.

**Comment by pushkal-symsoft** [comment]
Thanks for response. 
I got it resolved by enabling that feature mentioned in that article. I was then able to use the contact lens API for real time transcripts https://docs.aws.amazon.com/connect/latest/adminguide/contact-lens-api.html
