### ISSUE TITLE
How to Implement Silent Monitoring and Barge-In Using Amazon Connect Streams API in a Custom Supervisor Dashboard?

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-streams#912]
I am developing a custom supervisor dashboard using the Amazon Connect Streams API. The primary goal is to provide supervisors with the ability to perform silent monitoring and barge-in functionality on ongoing calls.

**Current Setup:**

- I am using the Amazon Connect Streams API to manage agent interactions.
- I can successfully retrieve contact details, such as ContactId, using the GetCurrentMetricData API which i wrote in Lambda function.
- I want to enable supervisors to silently monitor active calls and barge-in.

**Problem:**

I haven't found any direct methods within the Amazon Connect Streams API documentation that support silent monitoring or barge-in functionality for another agent. I'm looking for guidance on how to implement them effectively.

**Comment by tannera926** [comment]
This looks like a duplicate: 
https://github.com/amazon-connect/amazon-connect-streams/issues/919
https://github.com/amazon-connect/amazon-connect-streams/issues/921

You can't use the Streams API to initiate silent monitoring, you have to use a the public API [MonitorContact](https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html) for this. This is because in the default CCP, monitoring is initiated through the Real Time Metrics page and not in the CCP.

Once monitoring has been initiated, you can barge in to a call or chat using the [contact.bargeIn()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactbargein) Streams API and you can switch back to silent monitoring in a call or chat using the [contact.silentMonitor()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactsilentmonitor) Streams API.
